language: java
env:
  global:
    - secure: "AoH6IfJwxtReNcKvskIv+tTLbbpkZi7E+CJPN9X007V8ozF+Ve0KblqJRAWfBxivbNNzqF3ZTlOxavzf2Lt7LI8H4Pp4krESRd58eCTCdj27tas44R2sc2AgrU1XuHaTsovYDKSRbQnHpnxwxcAPeP/f/14rWBQ2ejfadTt6QTk="
    - secure: "19374220-fef6-4897-8922-fa92f7142053"

before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash

deploy:
  provider: heroku
  api_key:
    secure: dabyIuFMfrnVX9eEMKb07B6X7Gp7ljHUb9sfQMVAIO2lAg/+6uV6mHK7csT2xTyVWyw67F/e7Si1ZmelcMDjFfFrqd2HoK+JH+Nv2mxC6KMpoBPPgdoeWZcuu9VE44FP9Tk3GcXSt1zlCKE1oVzQXYIfg2YoJFgRa0SQifn2B8E=
  app: tictactoes
  on:
    repo: 0xabad1deaf/Lateterm
